version: '3.7'
services:
  container-test:
    build: .
    image: ragedunicorn/container-test:${CONTAINER_STRUCTURE_TEST_VERSION}-dev
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.container-test.environment: "dev"
      com.ragedunicorn.container-test.description: "Google Container Structure Test"
